/* PROGRAM #5
   This program generates two semantic errors on lines 24 and 33.

   The first error is generated because the function "func2"
   is already declared on line 15.

   The second error is generated because the variable "x" is
   already declared in the local scope on line 29.
*/

int x;
int y;
int z;

int func2(int a) {
    return a * 4;
}

void func1(int x, int y) {
    output(x + y);
    output(func2(x + y));
}

bool func2(int b) {
    return b * 8 > 10;
}

void main(void) {
    int x;
    int y;
    int z;

    int x;

    x = (y - z) / x;
    func1(x, z);

    output(x);
}
